History Descriptions
jupytercalpoly/Jupyter-Bifrost pull request #113
Opened 2021-08-17 17:49 UTC by Waidhoferj

Added descriptions and numbering to history tab

## Changes
Custom messages for the following actions
- Deleting a pill
- Assigning a pill
- Choosing a chart
- Applying a filter

Added numbers in chronological order where 1 is the earliest entry

## Test
- Perform actions that create custom messages in history and see results. 
- Verify that "Graph Changed" is not one of the messages. This is a fallback message and indicates that there is a missing description.

2021-08-17 19:04 UTC, jahn96 requested changes
Couldn't build the extension due to the error below

2021-08-17 19:04 UTC, jahn96 commented on src/components/Sidebar/Tabs/DataTab.tsx
> +      `Assigned the '${field}' field to ${activeEncoding}`
Active Encoding is undefined

2021-08-17 20:46 UTC, Waidhoferj commented on src/components/Sidebar/Tabs/DataTab.tsx
> +      `Assigned the '${field}' field to ${activeEncoding}`
Sorry about that

2021-08-17 23:35 UTC, jahn96 requested changes
Need to rebase main

2021-08-18 00:31 UTC, jahn96 approved these changes
Other than this comment, all look good!

2021-08-18 00:31 UTC, jahn96 commented on bifrost_jupyter_extension.json
> +}
Sorry if this confuses you. I don't think we need `bifrost_jupyter_extension.json` and `bifrost.json` in our repo.

2021-08-18 00:37 UTC, merged