Code Export
jupytercalpoly/Jupyter-Bifrost pull request #28
Opened 2021-07-07 18:50 UTC by Waidhoferj

**Vega aggregations can be exported to pandas code!**

## Changes
- Added support for 16 / 22 of the aggregations in Vega for code export.
- Added support for quantitative and categorical filtering code export.
- 
## Limitations
Since we do not have tracing integrated with the library, we currently use `df` as the dataframe variable name. The user has to manually swap this out if their data frame was not named `df`.

## Testing
1. Plot a DataFrame and open the Graph in Bifrost.
2. For each of the following, apply the change to the graph, click export code and run the code to see if the outputted data frame appears reasonable in form:
 - Apply a min/max filter to a quantitative variable
 - Apply a membership filter to a categorical variable
 - Try out several aggregations with a quantitative variable, ensuring that they do not produce errors when run.

2021-07-07 21:16 UTC, jahn96 commented on src/modules/VegaPandasTranslator.ts
> +               return [`group_fields = $df.columns.to_list()`,
I think group_fields should be the one in the other axis. For example, if the graph has sepal_width on X axis and sepal_length on Y axis and is being averaged on the X-axis, then the group field should be sepal_length. The filtered points on the graph and the output from the exported pandas code do not match up in the current way.

2021-07-07 21:18 UTC, jahn96 commented on src/modules/VegaPandasTranslator.ts
> +                    query = `(${DF}['${filterConfig.field}'].isin([${filterConfig.oneOf.toString()}]))`
Need quotes around each oneOf

2021-07-07 21:25 UTC, jahn96 requested changes
I made a few comments. Also, I think there is a bug in history where the different filter overwrites the filter history

2021-07-07 21:57 UTC, Waidhoferj commented
Got the first two. I'll review yours and then check out the history bug.

2021-07-08 18:06 UTC, Waidhoferj commented
Changes made to history:
- History shows up in reverse chronological order (newest at the top)
- Selecting from a search filtered field no longer throws an error.
- History of your current edits is temporarily saved as you navigate the History tab

Search bar results were updated from a `string[]` to `{choice: string, index: number}[]` in order to deal with cases where there are duplicate choices that point to different data. In the history tab, two entries could have the same description, but contain different filters and present different graphs.

2021-07-08 20:58 UTC, jahn96 commented
1. Maybe rename `Apply Changes` to `Save in History`
2. Search functions a little strangely. Here is the gif. I found it weird that it didn't show me `petal length vs sepal width`. I fixed something related to this on search bar on my PR. Let me know if you also see this after rebasing the pr.
<img src="https://user-images.githubusercontent.com/15991814/124980378-2705d600-dfe9-11eb-87b7-2425288f1f22.gif" width="250" height="250"/>
3. In history tab, there is a strange behavior. After hitting `apply changes` on one of the previous history and add one more change to the history, it seems to add two duplicate changes. To reproduce, refer to the gif below.
<img src="https://user-images.githubusercontent.com/15991814/124989576-1c9d0980-dff4-11eb-9d8b-06395008d0af.gif" width="250" height="250"/>

2021-07-08 22:21 UTC, jahn96 commented
Build failure happened because sklearn and load_iris are not installed. We can add them as dependencies in build.yml. But, for now, I think it looks good!

2021-07-08 22:22 UTC, jahn96 approved these changes

2021-07-08 22:22 UTC, merged