Graph Data Pills
jupytercalpoly/Jupyter-Bifrost pull request #63
Opened 2021-07-28 21:56 UTC by Waidhoferj

**Add a new pill type `GraphPill` to match the latest pills from the Figma Prototype.**
<img width="263" alt="Screen Shot 2021-07-28 at 2 56 37 PM" src="https://user-images.githubusercontent.com/33008436/127401446-0495ac40-5e48-4a34-b4f4-7adfd1ba615e.png">

## Changes

- [ ] Add filters to pill
- [ ] Add aggregations to pill
- [ ] Add pill header
- [ ] Handle events associated with pill
- [ ] Rewrite axis-click logic to target new pill structure for selection

2021-07-30 00:01 UTC, Waidhoferj commented
## Todos
- When the encoding is clicked, open up the same encoding choice drawer as the add button, but just assign the new encoding to the object of the old one and delete the old encoding.
- When the field is clicked, open up the variable selection menu. On item click, find the encoding with that field and replace the field name with the new one.

2021-08-02 20:52 UTC, Waidhoferj commented
# Testing
- Verify that you can change encoding and field
- Verify that pills can be deleted
- Add a pill encoding, click on the empty tile and pick a field
- Verify that filter labels are added to pill when applied on filter screen
- Verify that 2 encodings with the same field get both of their filters updated when one is updated.

2021-08-02 22:53 UTC, jahn96 requested changes
Categorical variable shouldn't have aggregate icon.
I think the UI is a little different from the pill snap shot above. Is this going to be in another PR?

2021-08-03 00:05 UTC, Waidhoferj commented
Ah yeah I missed the `oneOf` checkbox icon for the categorical pill as well. Thanks for flagging this.

2021-08-05 17:21 UTC, jahn96 approved these changes
LGTM!

2021-08-05 17:21 UTC, jahn96 commented on src/components/Sidebar/Tabs/VariablesTab.tsx
> +  const [pillsInfo, setPillsInfo] = useState<PillState[]>([]);
I think this is great!

2021-08-05 17:29 UTC, merged