Performance Sampling
jupytercalpoly/Jupyter-Bifrost pull request #94
Opened 2021-08-09 23:56 UTC by Waidhoferj

Added sampling to the Onboarding Screen.

## Changes
- Added `graph_data_config` object that controls sampling on the `graph_data` object.
- Added automatic sampling when the Onboarding screen mounts and dismounts.

## Testing
- You could add a print statement to `update_dataset` to see how the graph data gets updated
- Or visually confirm that clicking the chart adds more data.

2021-08-11 17:23 UTC, Waidhoferj commented
@jahn96 I cannot reproduce the issue

2021-08-12 23:04 UTC, jahn96 requested changes

2021-08-12 23:04 UTC, jahn96 commented on bifrost_jupyter_extension/bifrost.py
> +        data = self.get_data(df, 10)
This needs to be matched with 100

2021-08-13 18:08 UTC, jahn96 approved these changes
LGTM!

2021-08-13 21:28 UTC, merged