Bifrost sizing
jupytercalpoly/Jupyter-Bifrost pull request #96
Opened 2021-08-10 19:42 UTC by jahn96

- [x] Change the size of the view when facet is added
- [x] Have the view fit to the graph content
    * Graph area in grid doesn't have a fixed height
    * To prevent the cut when the name of the categories are long
 
##Future Work
* Resizing the graph

2021-08-10 19:44 UTC, jahn96 commented
Resizing the graph did not work that well. I will just put it on hold and come back to it later, if necessary. Feel free to tackle this if you want.

2021-08-11 20:46 UTC, Waidhoferj requested changes
The new sizing logic doesn't seem to work as intended:
<img width="966" alt="Screen Shot 2021-08-11 at 1 43 24 PM" src="https://user-images.githubusercontent.com/33008436/129100662-d553851c-5126-43cd-8283-0f74daf5602b.png">
Faceted graphs push the sidebar off of the screen so it is inaccessible.


https://user-images.githubusercontent.com/33008436/129100752-9da3e38f-9939-4d30-9572-aabaa8c1650e.mov

The ChartChooser side scroller has chart instances concealed offscreen because the widget is overflowing its bounds.

2021-08-13 18:20 UTC, jahn96 commented
The sizing was calculated based on only when the left sidebar is collapsed. The possible solution is to get the size of the sidebar on mount and calculate the width. Downside with this is that it doesn't change the width dynamically when the sidebar grows or shrinks.

2021-08-13 22:10 UTC, Waidhoferj commented
Since CSS is giving us issues, we could listen for the `resize` event and get the with as state in the React widget, then set the width and the height of the chat chooser manually.

2021-08-17 21:19 UTC, Waidhoferj requested changes
When the columns collapse into rows, the side scroller doesn't take up the whole horizontal space, which makes is hard to view the entire width of a single graph. Maybe theres an issue in the resizing logic? We could just take the `boundingClientRect` of the widget container.


https://user-images.githubusercontent.com/33008436/129802072-d8f96fd2-aee4-4a72-ba2f-824a7ae42184.mov

2021-08-18 00:54 UTC, Waidhoferj requested changes
One quick change

2021-08-18 00:54 UTC, Waidhoferj commented on src/components/Onboarding/ChartChooser.tsx
>      height: 300px;
There is still a vertical scroll on the suggested charts when the columns collapse to rows. To fix this, increase the height a bit.
```suggestion
    height: 315px;
```

Other than that looks great!

2021-08-18 17:16 UTC, Waidhoferj approved these changes
LGTM

2021-08-18 17:37 UTC, merged